//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:sch=&quot;http://www.tibco.com/schemas/Clientes/Resources/EIM/Common/Schema.xsd&quot; xmlns:ser=&quot;http://www.compensar.com/services_psa080_administrarclientes&quot;&gt;
        ///   &lt;soapenv:Header&gt;
        ///      &lt;sch:headerMessage&gt;
        ///         &lt;sch:userName&gt;1022948279&lt;/sch:userName&gt;
        ///         &lt;sch:idAplicacion&gt;SWPR108&lt;/sch:idAplicacion&gt;
        ///      &lt;/sch:headerMessage&gt;
        ///   &lt;/soapenv:Header&gt;
        ///   &lt;soapenv:Body&gt;
        ///      &lt;ser:CrearVinculacionClienteRequest&gt;
        ///         &lt;cre [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string AdministrarClientes_Desvincular_Empresa_Request {
            get {
                return ResourceManager.GetString("AdministrarClientes_Desvincular_Empresa_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:sch=&quot;http://www.tibco.com/schemas/Clientes/Resources/EIM/Common/Schema.xsd&quot; 
        ///xmlns:ser=&quot;http://www.compensar.com/services_psa080_administrarclientes&quot;&gt;
        ///   &lt;soapenv:Header&gt;
        ///      &lt;sch:headerMessage&gt;
        ///         &lt;sch:userName&gt;1022948279&lt;/sch:userName&gt;
        ///         &lt;sch:idAplicacion&gt;SWPR108&lt;/sch:idAplicacion&gt;
        ///      &lt;/sch:headerMessage&gt;
        ///   &lt;/soapenv:Header&gt;
        ///   &lt;soapenv:Body&gt;
        ///      &lt;ser:CrearVinculacionClienteRequest&gt;
        ///         &lt;c [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Xml {
            get {
                return ResourceManager.GetString("Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Cliente xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///               &lt;legalID&gt;900877788&lt;/legalID&gt;
        ///               &lt;tipoIdentificacion&gt;2&lt;/tipoIdentificacion&gt;
        ///               &lt;id&gt;9999805069127038&lt;/id&gt;
        ///               &lt;datosEmpresa&gt;
        ///                  &lt;razonSocial&gt;-&lt;/razonSocial&gt;
        ///                  &lt;nombreComercial&gt;-&lt;/nombreComercial&gt;
        ///                  &lt;motivoInactivacion&gt;
        ///                     &lt;id&gt;0&lt;/id&gt;
        ///         [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string xmlCliente {
            get {
                return ResourceManager.GetString("xmlCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;headerMessage xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;userName xmlns=&quot;http://www.tibco.com/schemas/Clientes/Resources/EIM/Common/Schema.xsd&quot;&gt;1022948279&lt;/userName&gt;
        ///  &lt;idAplicacion xmlns=&quot;http://www.tibco.com/schemas/Clientes/Resources/EIM/Common/Schema.xsd&quot;&gt;SWPR108&lt;/idAplicacion&gt;
        ///&lt;/headerMessage&gt;.
        /// </summary>
        internal static string xmlHeader {
            get {
                return ResourceManager.GetString("xmlHeader", resourceCulture);
            }
        }
    }
}
